### ISSUE TITLE
Filter based on Rule Usage Last Hit

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#132]
### Is your feature request related to a problem?

It would be very nice to be able to filter based on the Rule Usage Last Hit for rules, in particular based on a timeframe (e.g.,not hit since Sept 15, 2020 so anything from Sept 14, 2020 or older would match).

Also, include a switch to include the hit columns in the Excel export action.

### Describe the solution you'd like

Filter policies for actions.  For example, tag old rules (90 days, 180 days, 1 year, etc.), delete these "unused" rules older than a certain timeframe (e.g., 1 year), tag rules that started appearing as unused when the COVID lockdown began in March 2020.

For the Excel export switch, this would be needed for reporting purposes to show these stale rules (in particular for audit purposes where we show that they were identified and then deleted).

### Describe alternatives you've considered

Manually check all rules' last hits.  This is required because even Used or Partially Used rules could have stale last hits.

I also do the unused rule filter scans but as far as I can tell those only match truly unused rules.

### Additional context

We have an audit requirement to remove stale rules.  As part of this process, we periodically scan & tag rules based on time frames (90 days, 180 days, 1 year, etc.).  Also, we mark rules keep that we don't want deleted (e.g., rules in a DR datacenter that rarely, if ever, get hit) and we disable stale rules for 90 days prior to deletion which are two related tasks to use the script for once the rules have been tagged for deletion.

**Comment by swaschkut** [comment]
thanks for highlighting this use case.
Please allow me some time to check how this feature requisition can implement

**Comment by bethatasitmay** [comment]
FYI, I noticed this page on pan.dev that references exporting the info to a csv using the PAN Python SDK:

https://panos.pan.dev/docs/apis/panos_tutorials_rule_hit_count

**Comment by swaschkut** [comment]
as I did not found another way to inform you:
a very old bug found by you for pan-configurator is now fixed:
https://github.com/PaloAltoNetworks/pan-os-php/issues/149

this was for pa_rule-edit 'filter=(user has DOMAIN\USER )'

please be aware that no additional double quote are allowed/needed


the feature request for "Filter based on Rule Usage Last Hit" is still under validation

**Comment by bethatasitmay** [comment]
Cool, thanks!

**Comment by madmann26** [comment]
To get by, could you not export the rules from webui, then evaluate what rules you want disabled, then read the csv for rulename and take action?

I would need to test it but that should work.

**Comment by swaschkut** [comment]
implemented with PR: 
https://github.com/PaloAltoNetworks/pan-os-php/pull/322

pa_rule-edit in=api://FW-MGMT-IP 'filter=(timestamp-last-hit.fast < - 90 days)'

**Comment by swaschkut** [comment]
for the additional request:
"For the Excel export switch, this would be needed for reporting purposes to show these stale rules (in particular for audit purposes where we show that they were identified and then deleted)."

I recommend to run this script and tag it;
the Excel export can be done by using the tag as a filter
