### ISSUE TITLE
Issue with getting new token post password reset

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#137]
## Describe the bug

I'm unable to update my token key after a recent Windows credential update.  This happened previously as reported & fixed on the Live Community page.

(our firewalls/Panorama authenticate against AD via RADIUS)

After running a command (I specifically tried pa_rule-edit and pa_key-manager) I get an error (see Current Behavior)

## Expected behavior

A new token key should be generated and that's that - commands beging working normally.

## Current behavior

>pa_key-manager add=panorama.domain.com debugapi shadow-apikeynohidden nohiddenpw

***********************************************
*********** key-manager.php UTILITY **************

 - PAN-OS-PHP version: 2.0.12 [WIN]
 - loading keystore from file in user home directory...

 - requested to add Host/IP 'panorama.domain.com'

####################################
For PAN-OS version < 9.0 please use additional argument 'shadow-apikeynohidden' in your script command

####################################
** Request API access to host 'panorama.domain.com' but invalid credentials were detected'
** Please enter API key or username below and hit enter:
username
** you input user 'username' , please enter password now, password is displayed in plaintext :
ClearTextPassword

* Now generating an API key from 'panorama.domain.com'...
API call: "https://panorama.domain.com/api/?key=&type=keygen&user=username&password=ClearTextPassword"

####################################
For PAN-OS version < 9.0 please use additional argument 'shadow-apikeynohidden' in your script command

####################################

* ** ERROR ** * HTTP API returned (code : 403); <response status = 'error' code = '403'><result><msg>Invalid credentials.</msg></result></response>

I also tried it without the nohiddenpw parameter and a pa_rule-edit command that normally works which both prompted for new credentials and ended with the same result.

## Possible solution

Sorry, not my area of expertise.

## Steps to reproduce

1. Change credentials or delete an existing key (backing up first, of course)
2. Run any command including pa_key-manager
3. Enter username when prompted
4. Enter password when prompted

## Context

We run scripts weekly if not daily and at this moment I'm trying to tag all rules with old, expired schedules for rule/schedule cleanup.  I also have other things to do this week that I hope to get to :-)

## Your Environment

- Version used: 8.1.19
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Running PAN-OS-PHP (updated before bug report); current Chrome & Edge
- Operating System and version (desktop or mobile): Windows 10
- Link to your project: N/A

**Comment by swaschkut** [comment]
thanks for reaching out,
during a test on a LAB Windows 10 machine with updated pan-os-php-windows-package I can not see the problem you are running into.

you are aware of, that you need to put in the argument 'shadow-apikeynohidden' for every single script run? this is because you are running PAN-OS 8.1.X which is not supporting sending PAN-OS API key via POST method

**Comment by swaschkut** [comment]
updating an PAN-OS API-KEY is working this way:

pa_key-manager delete=panorama.domain.com
pa_key-manager add=panorama.domain.com shadow-apikeynohidden

or in short
pa_key-manager test=panorama.domain.com shadow-apikeynohidden

**Comment by bethatasitmay** [comment]
shadow-apikeynohidden is in the command I posted - it's hard to see I think :-)

pa_key-manager add=panorama.domain.com debugapi **shadow-apikeynohidden** nohiddenpw

**Comment by swaschkut** [comment]
copy past this link, with real username password, into your web browser:
https://panorama.domain.com/api/?key=&type=keygen&user=username&password=ClearTextPassword

does it give you the API-KEY back or the same error message?

if It is the same error message, then it is not related to the PAN-OS-PHP framework

**Comment by bethatasitmay** [comment]
Same error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response status="error" code="403">
<result>
<msg>Invalid credentials.</msg>
</result>
</response>

**Comment by bethatasitmay** [comment]
eh, didn't post right:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response status="error" code="403">
<result>
<msg>Invalid credentials.</msg>
</result>
</response>`

**Comment by bethatasitmay** [comment]
Hmmm, I think you get the idea, lol.

So, if not the tool, can you tell me where I go from here?

**Comment by swaschkut** [comment]
with this document link:
https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-panorama-api/get-started-with-the-pan-os-xml-api/get-your-api-key.html

and mention that you are using this URL:
https://panorama.domain.com/api/?key=&type=keygen&user=username&password=ClearTextPassword

you can open a Palo Alto Networks TAC case.

To avoid any push back, I would not mention about any usage of PAN-OS-PHP or any other none Palo Alto Networks TAC supported scripts.

I am closing this issue, as it is not related to PAN-OS-PHP framework.

**Comment by bethatasitmay** [comment]
Just to close the loop, this was caused by my account in Panorama (Panorama | Administrators) being locked somehow (no idea how it got locked - I had logged in earlier in the day successfully).  Once unlocked everything started working.
