### ISSUE TITLE
Automatic credential prompt didn't happen post password change

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#336]
## Describe the bug

I had to change my admin user password (authenticated via RADIUS with AD on the backend) recently and when I ran a pa_address-edit command (first UTIL command since the change) I did not get prompted to update my API key.

## Expected behavior

Normally, after a password change, when running a UTIL command, I get prompted to update my API key in the flow of the command.

## Current behavior

~>pa_address-edit in=api://panorama.domain.com location=any actions=addObjectWhereUsed:hostname2 'filter=(name eq hostname1)' auditcomment='ticket info'

***********************************************
*********** address-edit.php UTILITY **************

 - PAN-OS-PHP version: 2.0.25 [WIN] [5.6.34]

####################################
For PAN-OS version < 9.0 please use additional argument 'shadow-apikeynohidden' in your script command

####################################

* ** ERROR ** * HTTP API returned (code : 403); <response status = 'error' code = '403'><result><msg>Invalid Credential</msg></result></response>

 *** Backtrace ***
0 ****
       backtrace_print()
       ::C:\dev2\pan-os-php\lib\pan_php_framework.php line 558
1 ****
       derr()
       ::C:\dev2\pan-os-php\lib\misc-classes\PanAPIConnector.php line 405
2 ****
       findOrCreateConnectorFromHost()
       ::C:\dev2\pan-os-php\lib\misc-classes\PH.php line 420
3 ****
       processIOMethod()
       ::C:\dev2\pan-os-php\utils\lib\UTIL.php line 715
4 ****
       UTIL::inputValidation() @
           C:\dev2\pan-os-php\utils\lib\UTIL.php line 687
5 ****
       UTIL::init_arguments() @
           C:\dev2\pan-os-php\utils\lib\UTIL.php line 215
6 ****
       UTIL::utilInit() @
           C:\dev2\pan-os-php\utils\lib\UTIL.php line 127
7 ****
       UTIL::utilStart() @
           C:\dev2\pan-os-php\utils\lib\UTIL.php line 120
8 ****
       UTIL::__construct() @
           C:\dev2\pan-os-php\utils\address-edit.php line 35
9 ****
       require_once()
       ::Command line code line 1

## Possible solution

No idea :-)

I was able to workaround it by using pa_key-manager delete/add.

## Steps to reproduce

1. Change password in AD (or I suppose delete the API key)
2. Run a UTIL command
3. No credential prompt so command fails

## Screenshots

See above

## Context

See above

## Your Environment

- Version used: 9.1.11-h2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): PAN-OS-PHP console
- Operating System and version (desktop or mobile): Windows 10 20H2

**Comment by swaschkut** [comment]
as you changed your password on AD, the APIKEY stored in .panconfigkeystore is still your old one.
bringing the error message: "Invalid Credential" is actually the default behaviour.

I see this as a feature request

**Comment by bethatasitmay** [comment]
In the past (all the way up to my just-prior pw change which would've been in September) when I ran a command post-password-change I was prompted to enter my credentials within the command stream.

Unfortunately, I don't have any screenshots I can show you reflecting this.

Oh, one other thing that changed was upgrading from v8.1.19 to v9.1.11-h2.  Could it be that the lack of the shadow-apikeynohidden parameter is related?  The just-prior change was on v8.1.19.

**Comment by bethatasitmay** [comment]
From a previous comment in the LIVEcommunity thread, I would see this line:

** Request API access to host 'lv-pamgmt01.dcswins.com' but invalid credentials were detected'

...followed by separate prompts for username and password as it does with pa_key-manager add:

 ** Please enter API key or username [or ldap password] below and hit enter:

and

** you input user <username from above> please enter password now password is hidden ::

**Comment by swaschkut** [comment]
behaviour changed with;
https://github.com/PaloAltoNetworks/pan-os-php/pull/337
