### ISSUE TITLE
Unable to read from file

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#356]
## Describe the bug

Unable to use 'filter=(rule name is.in.file:test.txt)' to pull in a list of rule names to take action against.

Full command -

pa_rule-edit in=api://*.com location=* actions=securityProfile-Group-Set:* 'filter=(rule name is.in.file:test.txt)'

(* represents obfuscated data for privacy purposes)

Error - 

**ERROR** Rule filter parser: unsupported operator name 'name' in expression 'rule name is.in.file:test.txt'

**Comment by swaschkut** [comment]
you are using the wrong syntax for this.
filters are always defined in a two or three steps process:

pa_rule-edit in=api://.com location= actions=securityProfile-Group-Set:* 'filter=(name is.in.file test.txt)'

how you can check this;
pa_rule-edit listfilters

will display something like this:

...
* name
    - contains                          
    - eq                                : returns TRUE if rule name matches the one specified in argument
    - eq.nocase                         
    - is.in.file                        : returns TRUE if rule name matches one of the names found in text file provided in argument
    - regex                             : returns TRUE if rule name matches the regular expression provided in argument
....


so the first part could only be:
'filter=(name

combining with the second;
'filter=(name is.in.file

and then following the last argument:
'filter=(name is.in.file FILENAME)'

**Comment by madmann26** [comment]
Ohhhhhhhh, the syntax changed.

I just tested it, it does indeed work.

You can close this as user error @swaschkut. Thanks for the help!
