### ISSUE TITLE
Description add/remove prefix/suffix

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#407]
### Is your feature request related to a problem?

I recently migrated a Juniper SRX via Expedition and when I converted address objects to shared it corrupted the descriptions of 800+ address objects but combing a lot of different objects' descriptions up to the maximum field length (255 characters I believe.  Expedition was a lot worse - the migration truncated them).  While this is specific to address objects, it could prove useful for other items.

### Describe the solution you'd like

Unfortunately, I can't give an example in a public place but the corruption is fairly consistent - it's always the same words being added.  The last character before end of field varies depending on what was originally in the field I can work around that.

So, I'd like to be able to do something like the rules name options - append/prepend and add/remove prefix/suffix.  This is true of any description for objects and rules but I know some options do exist (e.g., append).

### Describe alternatives you've considered

The only other way I would know how to do it is manually remove the extraneous characters.

### Additional context

Currently I manually clean up the descriptions as I come across them.  However, I just checked and I have 740 objects remaining to be cleaned up.

**Comment by swaschkut** [comment]
Please check if the new action help you out with your request:


**pan-os-php type=address 'actions=(description-replace-character:OLDone,NEWone)'** 

the above command is exact to the old one below, but the old command is deprecated:
pa_address-edit 'actions=(description-replace-character:OLDone,NEWone)'

**Comment by bethatasitmay** [comment]
So, if I wanted to delete the extraneous text but leave whatever was there before, the NEWone would just be blank (no character)?

For example

(description-replace-character:,OLDone,)

I have a comma before Extra as that's how the corruption starts.

**Comment by swaschkut** [comment]
Please provided exact example what you like to do, and I can give an exact answer.

If you can create a DEMO description and point out what you like to replace with "";
we can continue speaking about this.

If you like to replace an "," PAN-OS-PHP can not handle this, as "," is a separator and can not be "escaped";

**Comment by bethatasitmay** [comment]
Examples:

original-text,word1, word2, word3, word4, <repeated until end of field - 255 characters total)

Or, if the original description was blank:

word1, word2, word3, word4, <repeated until end of field - 255 characters total)

I can email you real examples if you like.

**Comment by swaschkut** [comment]
this is now improved and right now only available in Docker Container pan-os-php:develop,

or here:
https://github.com/swaschkut/pan-os-php

it will be published by next week

`pan-os-php type=address in=api://MGMT-IP 'actions=description-Replace-Character:$$comma$$word1' debugapi`

- for all address objects, description with ",word1" will be replaced with ""

$$comma$$ is a variable which is internally replaced with ","

**Comment by swaschkut** [comment]
published with version 2.0.42

**Comment by bethatasitmay** [comment]
Hi - sorry, I forgot about my issue and didn't notice it was fixed/closed.  I've posted a Q&A discussion topic about usage syntax.
