### ISSUE TITLE
Enhance tag-merger with option for "ignoreColor"

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#411]
1.	Tags – have an option to ‘ignoreColor’ for tag-merger; sameName but use ignoreColor

This is related to tag-merger when attempting to merge tags with upperlevel.

Message from pan-os-php -

* keeping object '/somelocation:tags/Tag:sometag'
    - object 'sometag' cannot be merged because it has an ancestor with different color
         ancestor name: 'sometag' DG: 'somelocation'  color: 'none'

**Comment by swaschkut** [comment]
thanks for reaching out.

I am planning to introduce additional DupAlgorithm:
DupAlgorithm=SameName

which checks only if Name is same, and does not focus on any other information configured for the TAG object

**Comment by madmann26** [comment]
Thanks Sven!

**Comment by swaschkut** [comment]
introduced with:
https://github.com/PaloAltoNetworks/pan-os-php/pull/414

please validate and give feedback

**Comment by madmann26** [comment]
> introduced with: #414
> 
> please validate and give feedback

Hi Sven,

I did a refresh on the repo but it does not seem to be available -

**ERROR** unsupported value for dupAlgorithm: sameaddress

I also do not see it when running:

pan-os-php type=tag-merger help

**Comment by swaschkut** [comment]
please check above, it is:
DupAlgorithm=SameName

the help is now also showing this

**Comment by madmann26** [comment]
> please check above, it is: DupAlgorithm=SameName
> 
> the help is now also showing this

Confirmed. This works as intended while ignoring the color assigned to the tag object.

Thanks Sven!
