### ISSUE TITLE
Enumerate All AddressObjects When Enumerating Nested AddressGroups

### ISSUE THREAD

**Issue by rebelfish** [PaloAltoNetworks/pan-os-php#426]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like an action added similar to 'showip4mapping' but enumerates ALL AddressObjects regardless of type. It would also be beneficial if the count of entries displayed accurately reflects the total number of AddressObjects found in the AddressGroup and any nested AddressGroups. 

Perhaps an action of 'showallmappings' or 'enumerateAll'. In my case, I had FQDN objects and while I wouldn't expect a DNS lookup to return the values, using the same format as used in 'actions=display' would work ('objName.  value: fqdn')

### Describe alternatives you've considered

I currently have to run a couple of different commands to get an accurate count of AddressObjects and have them enumerated

**Comment by swaschkut** [comment]
have you checked the already available feature:

`pan-os-php type=address in=api://MGMT-IP 'actions=exporttoexcel:FILE.html,ResolveIP|NestedMembers' 'filter=(object is.group)'`

**Comment by swaschkut** [comment]
since today 20220513 your FR is available in the develop container:

`docker run -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

`pan-os-php type=address in=api://MGMT-IP 'actions=exporttoexcel:FILE.html,ResolveIP|NestedMembers' 'filter=(object is.group)'`

**Comment by swaschkut** [comment]
published with version 2.0.42
