### ISSUE TITLE
Issues with address-merger and FQDN to parent DG

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#430]
HI Sven -

For address-merging, I can’t seem to move ipv4 objects from a child DG to a parent DG where a FQDN exists (the object names are the same).

Result (whether I use pickfilter = ipv4 or fqdn)

- value 'ip-netmask-x.x.x.x'
   * keeping object '/x/AddressStore/Address:somefqdnname'
    - object 'somefqdnname' 'fqdn' cannot be merged because it has an ancestor with different value
         ancestor name: 'somefqdnname' DG: 'someDG'  value: 'somefqdnvalue'

Commands attempted –

pan-os-php in=api://x.x.x.x type=address-merger actions=move:tosomezone-name location=fromsomezonename allowmergingwithupperlevel 'pickfilter=(object is.fqdn)'

pan-os-php in=api://x.x.x.x type=address-merger actions=move:tosomezone-name location=fromsomezonename allowmergingwithupperlevel 'pickfilter=(object is.ipv4)'

pan-os-php in=api://x.x.x.x type=address-merger actions=move:tosomezone-name location=fromsomezonename 'pickfilter=(object is.fqdn)'

Hierarchy –

tosomezone-name
-	fromsomezonename

**Comment by swaschkut** [comment]
you scrambled a lot of commands:

pan-os-php type=address-merger - does not have argument "actions", where do you get this from?

If you are checking the help information you will find an argument called:
DupAlgorithm=SameAddress; which is predefined and used;

What you are searching is more or less a new DupAlgorithm=SameName;
If I remember correct, then you were requesting something similar for tag-merger

**Comment by swaschkut** [comment]
FR: add DupAlgorithm=SameName so that objects with same name get merged with fqdn objects

**Comment by swaschkut** [comment]
but there is for you also another feature available;

pan-os-php type=address actions=value-set-ip-for-fqdn

* value-set-ip-for-fqdn     | - replace FQDN with the IP
===========================
* value-set-reverse-dns     | - replace IP with the FQDN

**Comment by madmann26** [comment]
You're probably right Sven, I'll check it again. I tried a lot of things.

Thanks

**Comment by madmann26** [comment]
Sven,

2 commands got me where I wanted to be -

1. First running type=address actions=value-set-reverse-dns (this converted child DG objects from ipv4 to fqdn)
2. Then running type=address-merger DupAlgorithm=sameaddress moved the objects to the parent DG as I had wanted all along.


If 'samename' could be incorporated into address-merger like with tag-merger, it would be very helpful.

Thanks for your work.
