### ISSUE TITLE
FR-01032022-1 - ability to search for rules based on the number of ports they reference

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#506]
**Reason:**
Useful for targeting "wide open" port-based rules. Similar to auditors clamping down on rules with 10.0.0.0/8, 172.16.0.0/12 or 192.168.0.0/16 which are also considered "wide open", just one step above "any".

filter could be something along the lines of (service has.more.than X) where X will be the number of ports.

**Examples:**
rule X allows ports 1000-65000 (usually done when people are not sure about the exact range for random ports)
rule Y allows ports 1-65535 (often done to get around not being allowed to permit "any" port)
rule Z allows ports 5060-5061,16384-32767 (SIP and RTP port ranges, not to mention all the possible custom variations)

1) 'filter=(service has.more.than 16385)' would match XYZ rules (Z allows 16386 ports)
2) 'filter=(service has.more.than 60000)' would match XY rules
and so on

**Use Cases:**
1) ranges inside the rules are used to calculate the number of ports (max-min+1)
2) nested objects and groups are evaluated
3) all ports and ranges across multiple independent groups and objects inside each rule are evaluated and are added to the total per rule
4) deal with duplicate ports
    - for example: a rule has a service group with dozens of objects with ranges which overlap (obj-A 1000-65000, obj-B 1-65535)
    - the result should be 65535, not 129536
5) ability to differentiate between TCP and UDP
    - in case the filter is coupled with existing "is.tcp" or "is.udp" filters

**Sidenote:**
- some App-IDs will allow all the ports as well, but those can be identified using the "app" filter as long as people know which ones are the "permissive" App-IDs
- the ability to provide the calculated number in an Excel spreadsheet will be raised as a separate FR

**Comment by swaschkut** [comment]
introduced withPR:
#507
