### ISSUE TITLE
FR-07032022-1 - supress verbose output

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#511]
### Is your feature request related to a problem?

when executing the script against a large config file, the amount of output prevents scrolling all the way to the start, because the terminal window buffer isn't large enough (even at max).

### Describe the solution you'd like

 Is it possible to suppress the verbose output and just leave the initial message with PAN-OS-PHP version, platform confirmation, template, ruletype, filter sanitisation etc? And then at the end, keep the list of rules which match the filter, action processing, argument information etc. Basically supress everything in between

### Describe alternatives you've considered

tried increasing the scroll buffer to max, it wasn't enough.

### Additional context

![Image 199](https://user-images.githubusercontent.com/20437364/157006551-2e72b394-2d70-44cc-8410-0c5d57965b33.png)

![Image 200](https://user-images.githubusercontent.com/20437364/157006476-29e94228-c817-4543-a72d-a6c1d5832d6d.png)

**Comment by swaschkut** [comment]
as an intermediate workaround, did you try to write the stdout into a log file?

pan-os-php type=xyz 'actions=ABC' in=api://MGMT-IP **| tee logfile.txt**

**Comment by nexusops** [comment]
interestingly enough, that actually skips all the "warning" messages and the log contains only the content I highlighted in the screenshots. That helps, thank you.

**Comment by swaschkut** [comment]
if the warning messages are need for another run, please use this:

pan-os-php type=xyz 'actions=ABC' in=api://MGMT-IP **2>&1 | tee logfile.txt**

**Comment by swaschkut** [comment]
as most of the warning can be solved with:

`pan-os-php type=xml-issue in=input.xml out=output.xml`

and that also most of the warnings are normally related to duplicate address-/service-group. members, 
which are starting with PAN-OS 10.0 also create a commit error.

I will not change the behaviour.
