### ISSUE TITLE
FR-07032022-2 excel export enhancement

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#512]
### Is your feature request related to a problem?

The Excel export currently doesn't stipulate whether the rules are from pre or post-rulebase.

### Describe the solution you'd like

Is it possible to add an extra column "rulebase" which will simply contain "pre-rulebase" or "post-rulebase" strings for each rule? It will make reporting as well as subsequent work with the spreadsheet (such as command creation and scripting) much simpler. If it can't be added as a separate column due to the fact firewalls do not have pre and post rulebases, can this be at least added into the existing "location" column separated by space from the Device-Group name?

### Describe alternatives you've considered

the alternative is to manually separate the rules into pre and post rulebases to create commands to make changes to the rules

### Additional context

possible examples
dual column solution (firewall config would have that blank)
![image](https://user-images.githubusercontent.com/20437364/157038331-cae1e357-5b1a-4346-a560-754e9c912e27.png)

single column
![image](https://user-images.githubusercontent.com/20437364/157038344-37c9b05e-69b7-4254-99fa-497ba396f5c9.png)

**Comment by swaschkut** [comment]
#514
