### ISSUE TITLE
Bug-14032022-1 - default rules are not processed across multiple Types

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#521]
## Describe the bug

default rules are not processed when looking for Security Profile Group using the following commands
1) `pan-os-php type=rule in=CONFIG.XML 'actions=exporttoexcel:secprof-test.xls,ResolveAddressSummary' 'location=DG-NAME' 'filter=(secprof group.is SPG-NAME)'`
2) `pan-os-php type=securityprofilegroup actions=exporttoexcel:file.xls location=any in=CONFIG.XML`

## Expected behavior

default rules should be processed

## Current behavior

default rules are not processed and the filters return results without matching default rules

## Possible solution

add default-rules into the processed configuration

## Steps to reproduce

1. configure SPG in default rules
2. run the above commands
3. observer results, missing SPG references from default rules

**Comment by swaschkut** [comment]
this will be resolved with version 2.0.58 and is already available in develop Docker Container;

`docker run --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop `

**Comment by swaschkut** [comment]
introduced with PR: #659
