### ISSUE TITLE
FR - Add Address Range size filter in pa_address-edit

### ISSUE THREAD

**Issue by taddairpanw** [PaloAltoNetworks/pan-os-php#527]
### Is your feature request related to a problem?
**The problem:** I am dealing with an issue in a large Panorama environment where certain firewalls are unable to be upgraded due to policy cache memory issues. Policy Cache memory is being exhausted in part by very large address range objects that were imported during a migration from a previous vendor which have references in policy. For example - instead of using CIDR notation address objects they created 10.0.0.0-10.128.255.255. These objects are in Panorama's shared context and pushed to firewalls when policy references are made.

### Describe the solution you'd like
**Proposed Solution**: Add new filter capabilities to pa_rule-edit and pa_address-edit for Range Objects. 
**pa_address-edit** Add filter for "Range > X", where X is a quantity of address objects. For example, an address range of 192.168.1.0-192.168.2.255 would have 512 addresses in the range. Being able to filter for "range > 512" would allow the user to find all address range objects that contain >512 addresses.
**pa_rule-edit** Add a filter for src and dst "has.range" to help identify security policies that are referencing range objects. 

### Describe alternatives you've considered

I attempted to use the existing filters and actions to achieve what I would like, but the only functionality that exists (to the best of my knowledge) is identifying whether an object is a range or not. It does not include the ability to calculate how many addresses are in the range.

### Additional context

Ideally we would like to be able to find these large range objects and replace them with an equivalent or near-equivalent CIDR notation address object. I am not sure if that would be something easily coded as an action because many range objects could be non-CIDR addresses. For example 10.1.1.23-10.1.2.54 or something. I mainly want to find very large ranges to clean up policy references to them. 

Please let me know if anything does not make sense.
Thanks!

**Comment by swaschkut** [comment]
filter and action implemented with PR: 
#528 

UTIL type=address | introduce 'filter=(ip.count >,<,=! VALUE)' AND 'actions=create-range2network')

- display with filter usage:
`pan-os-php type=address in=[api://MGMT-IP] 'filter=(ip.count > 254) and (object is.ip-range)'`

- move from ip-range to ip-netmask:
`pan-os-php type=address in=[api://MGMT-IP] actions=move-range2network 'filter=(ip.count > 254 ) and (object is.ip-range)'`

**Comment by swaschkut** [comment]
information about not well documented 'subquery' filter:
`pan-os-php type=rule in=inputconfig.xml 'filter=(src has.from.query subquery1)' 'subquery1=(ip.count > 254)'`

for src/dst subquery are based on all available filters from "pan-os-php type=address listfilters"
