### ISSUE TITLE
PAN-OS-PHP Windows Package [no longer under maintanace]- PHP Fatal error in DIFF.php line 662

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#531]
1. Updated prior to loading console.
2. Ran the following command -

pan-os-php type=address-merger in=api://<removed> DupAlgorithm=sameaddress location=<removed> allowmergingwithupperlevel Stats 2>&1 | tee <removed>.txt

3. Immediate error -

PHP Strict Standards:  DeviceGroup and XmlConvertible define the same property ($xmlroot) in the composition of DeviceGroup. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in D:\Pan_Configurator\pan-os-php-windows-package\pan-os-php\lib\device-and-system-classes\DeviceGroup.php on line 916
PHP Strict Standards:  Template and XmlConvertible define the same property ($xmlroot) in the composition of Template. This
might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in D:\Pan_Configurator\pan-os-php-windows-package\pan-os-php\lib\device-and-system-classes\Template.php on line 131
PHP Fatal error:  Cannot use [] for reading in D:\Pan_Configurator\pan-os-php-windows-package\pan-os-php\utils\lib\DIFF.php
on line 662

4. Line 662 from DIFF.php

$this->$type['rulebase'][] = $entry;

**Comment by swaschkut** [comment]
can you please validate latest code if your PHP installation with Strict settings is working with the newest PAN-OS-PHP please

**Comment by swaschkut** [comment]
BTW;
the Windows package is no longer under maintenance.
I recommend to check the new standard of how PAN-OS-PHP can be running on Windows:


https://github.com/PaloAltoNetworks/pan-os-php/blob/main/READMEdocker.md

**Comment by swaschkut** [comment]
This is related to PHP strict setting, and fixed in latest PAN-OS-PHP version:
recommendation -> use PAN-OS-PHP Docker Container;

old PAN-OS-PHP windows package is vulnerable by external libraries
