### ISSUE TITLE
PAN-OS_PHP_Windows-Package - deprecated | Unable to run scripts after recent update

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#547]
## Describe the bug

I haven't used nor updated the tool in a few weeks and went to use it but decided to update it first.  Now all commands (using either the new or old formats - e.g., pan-os-php type=rule vs. pa_rule-edit) results output the same php error.

(C:\dev2 is my install directory)

## Expected behavior

I should get results - I tried previous commands and they don't work.

## Current behavior

I receive this output for all command attempts:

PHP Fatal error:  Cannot use [] for reading in C:\dev2\pan-os-php\utils\lib\DIFF.php on line 662

## Steps to reproduce

1. Run any command
2. See an almost immediate return of the error (none of the usual processing output lines)
3.
4.

## Screenshots

Example 1:

pan-os-php type=address in=api://panorama location=any actions=exportToExcel:Object-A-whereused.xls,WhereUsed 'filter=(name eq Object-A)
PHP Fatal error:  Cannot use [] for reading in C:\dev2\pan-os-php\utils\lib\DIFF.php on line 662

Example 2:

pan-os-php type=rule in=api://panorama location=all ruletype=security actions=display 'filter=(name contains rule-999)'
PHP Fatal error:  Cannot use [] for reading in C:\dev2\pan-os-php\utils\lib\DIFF.php on line 662

Even simply pan-os-php gives the same error.

## Context

The tool is unusable forcing me to manually perform the work I was going to automate.

## Your Environment

- Version used: 9.1.13-h3 (upgraded from 9.1.12-h3 since previous PAN-OS-PHP usage)
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome v100.0.4896.127 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 20H2 Build 19042, 1645
 FYI, here are the results of the update I did:

C:\dev2>git submodule update --remote
remote: Enumerating objects: 1326, done.
remote: Counting objects: 100% (1326/1326), done.
remote: Compressing objects: 100% (781/781), done.
remote: Total 1326 (delta 1016), reused 804 (delta 542), pack-reused 0Receiving objects:  98% (1300/132
Receiving objects: 100% (1326/1326), 683.28 KiB | 2.93 MiB/s, done.
Resolving deltas: 100% (1016/1016), completed with 120 local objects.
From https://github.com/PaloAltoNetworks/pan-os-php
   5a4d2ad..89d3025  main       -> origin/main
 * [new tag]         v2.0.36    -> v2.0.36
 * [new tag]         v.2.0.31   -> v.2.0.31
 * [new tag]         v2.0.30    -> v2.0.30
 * [new tag]         v2.0.32    -> v2.0.32
 * [new tag]         v2.0.33    -> v2.0.33
 * [new tag]         v2.0.34    -> v2.0.34
 * [new tag]         v2.0.35    -> v2.0.35
Submodule path 'pan-os-php': checked out '89d302539aeb8967cdbe0e04eae5ebaaa2cd5eeb'

**Comment by madmann26** [comment]
If this is on a Windows install, it's been deprecated. You need to use the docker version or a Linux install.

(I also find out this way)

**Comment by swaschkut** [comment]
the old Windows package is using PHP version 5!

I recommend for Windows this setup:
https://github.com/PaloAltoNetworks/pan-os-php/blob/main/READMEdocker.md

**Comment by bethatasitmay** [comment]
Ohhhh.....I wasn't aware Windows was deprecated (I'm way behind in reading my Github updates).  Shoot, I've got about 2,000 lines of past command history that I use (used) to build new runs, lol.

**Comment by bethatasitmay** [comment]
I'm quite the Docker neophyte - will I need an additional Windows license to run it this way?

**Comment by madmann26** [comment]
> I'm quite the Docker neophyte - will I need an additional Windows license to run it this way?

You can run Ubuntu under Windows as WSL. I built a dedicated Linux VM for mine.

**Comment by bethatasitmay** [comment]
Well, I know Linux even less, lol.

**Comment by bethatasitmay** [comment]
@madmann26 So, are you saying you run Ubuntu under WSL or something else?

**Comment by madmann26** [comment]
I run mine on CentOS 8.

**Comment by bethatasitmay** [comment]
Okay, but do you run it as a docker container or some other kind of VM (VMware, Kubernetes, Azure, Virtual Box, WSL, etc.)?

**Comment by swaschkut** [comment]
did you follow the Docker installation documentation and the Microsoft help information how to get Docker running?


Per default WSL is using Ubuntu, there is no need of using another Container with Ubuntu.

**Comment by bethatasitmay** [comment]
Here were the steps I followed:

1) Uninstall Docker Desktop and WSL & reboot
2) Install WSL & WSL2 per these sites and steps:

https://docs.microsoft.com/en-gb/windows/wsl/install-manual

Step 1
Step 2 didn't seem to have any action items so I followed this page:

https://docs.microsoft.com/en-us/windows/wsl/install

Then back to the first link for steps 3-5.

3) Reboot
4) Install Docker Desktop & reboot

Docker Desktop starts now (it didn't when I first installed it and based on the error messages I received I believe it was due to a bad WSL install) but there are no containers.

When you indicate "Docker installation documentation" to what are you referring?  I was just following your wiki flowchart.

**Comment by swaschkut** [comment]
So it now possible to run this after Docker Desktop is started on Console:

`docker run -v ${PWD}:/share -it swaschkut/pan-os-php:latest`

**Comment by bethatasitmay** [comment]
When I try running the docker command from PowerShell I get this error:

> docker
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ docker
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have checked the Windows path environment variable and docker isn't on it.

If you're talking about a container CLI, it would appear that I have no containers in Linux mode.  I just tried to switch to Windows mode and it gave me an error which killed my running Docker Desktop and now it's giving me the original error aboue WSL not being installed correctly.  The error before crashing did say to run the following command to access Windows containers:

Enable-WindowsOptionalFeature -Online -FeatureName $("Microsoft-Hyper-V", "Containers") -All

**Comment by bethatasitmay** [comment]
Well, my Docker Desktop and possibly WSL is all screwed up again.  I can't start it - I just get this error:

Failed to deploy distro docker-desktop to C:\Users\my-username\AppData\Local\Docker\wsl\distro: : 

Some WSL system related access rights are not set correctly. This sometimes happens after waking the computer or not being connected to your domain/active directory. Please try to reboot the computer. If not sufficient, WSL may need to be reinstalled fully. As a last resort, try to uninstall/reinstall Docker Desktop.

When I got that error the first time I had to uninstall/re-install WSL & Docker Desktop.

**Comment by bethatasitmay** [comment]
Oh, and I ran that command in my comment two back but it didn't help.

**Comment by swaschkut** [comment]
as mentioned earlier,
I can not help on Windows WSL;

The graph at this page:
https://github.com/PaloAltoNetworks/pan-os-php/blob/main/READMEdocker.md

and the information and process by following ONLY step 2-5 of this site;
https://docs.microsoft.com/en-gb/windows/wsl/install-manual

helped all the people who had problems by using Docker Desktop on Windows.

Please understand that I can not give support how to get WSL2 and Docker Desktop correctly installed on any Windows system.

**Comment by swaschkut** [comment]
I know that other people installed PHP8 on Windows and downloaded the Git repository.
But also this I can not support.

There are still plenty options available how to get PAN-OS-PHP back into running mode in your environment.

**Comment by bethatasitmay** [comment]
I've been thinking about this over the weekend.  Maybe I need to just dive into Linux.  I mean, I already have to for Expedition (although there's not much I have to do myself).

I'll experiment with trying to get it to work on Windows, but I don't know what controls my work laptop have that could cause issues with even trying to get it to work.
