### ISSUE TITLE
service-merger issue

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#550]
service-merger (group) does not appear to be working correctly if a child DG has less members than the parent DG, when merged, child DG overwrites/overrides parent DG that has more members.

Example -

ParentDG – 10 members
  ChildDG – 6 members

pan-os-php command ran -

‘pan-os-php type=servicegroup-merger in=api://http://x.x.x/ DupAlgorithm=samemembers location=x allowmergingwithupperlevel allowaddingmissingobjects’

pan-os-php type=service in=api://http://x.x.x actions=delete-force location=x 'filter=(object overrides.upper.level) and (object is.group)'

**Comment by swaschkut** [comment]
thanks for finding this:

until now this is improved in the Docker Container **swaschkut/pan-os-php:develop**

1) update if already locally available:
` docker pull swaschkut/pan-os-php:develop`

2) run develop Container:
`docker run -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

I am planning to publish this after your feedback and validation

**Comment by swaschkut** [comment]
if there is something not working, please reopen this one
