### ISSUE TITLE
outputformat set is not including duplicate objects in the delete statements when used with type=address-merger

### ISSUE THREAD

**Issue by taddairpanw** [PaloAltoNetworks/pan-os-php#568]
## Describe the bug
When using type=address-merger to merge duplicate objects and when using outputformatset as an option, the delete commands that are generated in the output file do not include specific objects in the source or destination fields in the rule-base. They simply delete the entire source or the entire destination. 

## Expected behavior
The expected behavior is to only delete the duplicate objects that are referenced in the policies. By deleting the entire source or the entire destination, you could delete non-duplicate objects and have a negative impact on an environment.

## Current behavior
The script appears to be generating one delete command per instance of duplicate object, it is just missing the output of the duplicate address name in each statement. Example:
`delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 54-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 54-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination
delete device-group "DevGroup-XXX" post-rulebase security rules "Rule 50-RT-1" destination`

## Possible solution
To fix the bug I believe should be a simple task. Whichever variable is being used to store the name value of the duplicate addresses, reference this in the delete statement output. There are multiple delete statements per rule so this tells me that the loop iteration is correct, the value of the duplicate object is simply missing. 

## Steps to reproduce
Run pan-os-php type=address-merger against a configuration file that contains duplicate address objects. Use the argument "outputformatset" to generate set commands that delete the duplicate objects and add the replacement objects. CTRL+F for the delete statements in the rulebases. It affects all rulebases from what I can see. My config has NAT policies and Security policies.  

## Screenshots
![Uploading image.png…]()

## Context
I am running this against a very large config to assist my environment with address deduplication. We cannot use the set commands in the change tracking system because of the risk of deleting legitimate non-duplicated objects.

## Your Environment
It's big. Multiple Panoramas and this is part of an environment-wide deduplication effort.

- Version used:
- PAN-OS-PHP version: 2.0.40 [UNIX]
- PHP version: 7.4.3

**Comment by swaschkut** [comment]
thanks Tom for finding this bug:

fixed with PR:
#569
