### ISSUE TITLE
Tagging option for util rule-merger

### ISSUE THREAD

**Issue by necebeci** [PaloAltoNetworks/pan-os-php#577]
### Is your feature request related to a problem?

We are reviewing the merger rules after each consolidation task. Some rules ,however correctly merged, may need to be split again due to admin practices and/or individual mgmt choices. Also we need to fix the merged descriptions acc to customer standards again manually.
Having a tag for merged rules makes would make it easier to review these rules.

### Describe the solution you'd like

Add an optional attribute in util rule-merger to tag all merged rules. It can be a tag named "merged" by default or we can specify the name at each run. Obviously we would need to check existence of that tag in that DG and create it if necessary.

### Describe alternatives you've considered

Filtering out the set output for merged rules and tagging them manually as an extra step

**Comment by swaschkut** [comment]
introduced with PR #592
