### ISSUE TITLE
FR-26052022-1 - add existing objects into the required group using "create-address-from-file"

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#578]
### Is your feature request related to a problem?

Currently, when the "create-address-from-file" script runs, it skips any existing objects. Not changing the value of the object is fine, but would it be possible for the script to take the existing object and add it into the requested object group?

### Describe the solution you'd like

example:
obj1,4.4.4.4,DNS-group

the script would detect obj1 as an existing object, it would skip the creation (just as it does now), but it would still add the object into DNS-group

**Comment by swaschkut** [comment]
please validate with newest PR:
#582 

and comment please
