### ISSUE TITLE
Bug-26052022-1 - Uncaught Error in "create-address-from-file"

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#579]
## Describe the bug

Tried to create an object called "nested-range-1" with IP 4.4.4.4. The object already exists and it's actually an object group. I suspect that's what might be triggering the error.

## Expected behavior

The same behaviour like whenever an existing object is detected, just a quick SKIP message informing the user about existence of the object. And (if possible) a note saying it'as actually a group.

## Current behavior

script ends in error

## Steps to reproduce

1. prepare a file for the "create-address-from-file"
2. put the following in the file [name_of_existing_object_group],[IP_address]
3. run the command pan-os-php type=address in=[source_config_with_the_existing_group].xml 'actions=create-address-from-file:[objects_file].txt' outputformatset=create-objects.txt

## Screenshots

output provided via Slack

**Comment by swaschkut** [comment]
fixed with PR:
#581
