### ISSUE TITLE
FR-26052022-2 Force object value re-write using "create-address-from-file"

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#580]
### Is your feature request related to a problem?

currently the script skips any existing objects

### Describe the solution you'd like

add a "Force" option to the command, which instructs the script to change the value of existing objects as long as they have the correct type. I believe currently the script accepts only ip-netmask type.

### Describe alternatives you've considered

The script currently clearly says which objects already exist so we just create the SET commands for adding them into the groups manually.

**Comment by swaschkut** [comment]
please validate with newest PR:
#582 

and comment please
