### ISSUE TITLE
Descriptions are not properly merged using type=rule-merger

### ISSUE THREAD

**Issue by necebeci** [PaloAltoNetworks/pan-os-php#583]
## Describe the bug

set output generated after rule merger cannot merge descriptions with multiple lines. Only the first line of comments are added to merged rule and the rest is ignored by panorama cli as unknown command

## Expected behavior

All the rule descriptions should be included in merged rule

## Current behavior

Panorama cli ignores the new lines and only includes the first line of comments

## Possible solution

This is possibly a limitation on PANOS CLI, if it's not possible to add multiline comments using cli the solution could be to merge them all in a single line and generate the set output accordingly.

## Steps to reproduce

Paste the command below in panos cli

> set device-group PLAYGROUND pre-rulebase security rules asd description "test
test1
test2"

## Screenshots

![Uploading Screen Shot 2022-05-30 at 12.36.49.png…]()
## Your Environment

root@d3f2975c6a8a:/share# pan-os-php version 
 - PAN-OS-PHP version: 2.0.42 [UNIX]
 - /tools/pan-os-php/utils
 - PHP version: 7.4.3

**Comment by swaschkut** [comment]
until now I assume this is still a PAN-OS issue, which is available for the last 10 years:
https://live.paloaltonetworks.com/t5/general-topics/how-to-escape-a-line-feed-in-login-banner-via-cli/td-p/14912

But I am trying to check what is possible to get the description more or less correct into the config, if "set commands" are used

**Comment by necebeci** [comment]
One idea, can we put a special character or a string while merging all different rule descriptions in a single line? If that's possible I can try to search and replace that special characters with a newline using XML API later on

**Comment by swaschkut** [comment]
what I found out is the suggestion to use '^M';
it is working find to use this in set commands. the only problem is that in the GUI it is also displayed as ^M and not as a new line

**Comment by swaschkut** [comment]
PR #586 

is adding ^M as a line break for "set commands"

this character can be then replaced by using mode API:

pan-os-php type=rule in=api://MGMT-IP  'actions=description-Replace-Character:-,$$newline$$' location=any
