### ISSUE TITLE
Bug-08062022-3 "create-address-from-file", force group = no, rewrite=yes/no

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#589]
## Describe the bug

source file for the object creation contains the following. These objects already exist in the config
obj-8.8.8.8,4.4.4.4,new-group-for-existing-objects
obj-10.10.10.10,20.20.20.0/24,new-group-for-existing-objects

when the "force group" argument is set to "no". And when all the objects, which are supposed to go into the same group, already exist, then there are no objects to be added into the group. However, because the group doesn't exist yet, the script generates a command to create a blank group. Unfortunately this command is not valid

set address-group "new-group-for-existing-objects" static

## Expected behavior

the correct command to create a blank static group is 
set address-group "new-group-for-existing-objects" static [ ]

additional information shared via Slack

**Comment by swaschkut** [comment]
correction:

the correct set command to crate a blank static group is:

`set address-group "new-group-for-existing-objects"`

**Comment by nexusops** [comment]
have you tried to commit that? Because I did :)

**Comment by swaschkut** [comment]
yes, I did. 
nevertheless I found another way.

fixed with PR #591
