### ISSUE TITLE
Timestamp filter not working as expected

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#607]
## Describe the bug

The timestamp filter does not appear to be working correctly - it is including items outside of the parameters.

## Expected behavior

The timestamp filter should only include the items indicated.

## Current behavior

I was trying to find unused rules older with a 180 days.  However, the results came back with timestamp-last-hit.fast sooner than that (in fact, rules with last hits of today).

Some background: this cluster was the replacement for several other clusters.  On the day of cutover (December 11, 2021), there are a lot of matches for that date as the last hit (there was a zone issue I had to fix).  These rules would have been marked unused otherwise.

## Possible solution

It's possible that I'm not using the filter correctly.  However, I tried it both ways (less than or greater than in different runs).  Less than 180 days is closer to accurate than greater than.  Greater than 180 days appears to return all security policy rules (I say appears because even though I'm limiting the location & ruletype I get back more rules than exist - for example, this firewall only has 3,480 explicit rules (plus the 2 implied) but the results come back with 3,484 rules.  Less than 180 days returns 2,174 rules.

I also tried it using a date instead of 180, but I received the same results.

## Steps to reproduce

<1>

I tried it this way first:

pan-os-php type=rule in=api://panorama location=DG1 ruletype=security actions=exportToExcel:last-hit-180-A.xls  'filter=!(timestamp-last-hit.fast < - 180 days)'

This produced 2,174 rules.  I spot checked a couple of rules and it looked OK so I ran my 'real' action (in this case, adding an UNUSED tag) and when I spot checked that I found rules that had been hit sooner than 180 days (one had a hit today).

<2>

So, I did greater than to see what would happen:

pan-os-php type=rule in=api://panorama location=DG1 ruletype=security actions=exportToExcel:last-hit-180-B.xls  'filter=!(timestamp-last-hit.fast > - 180 days)'

This produced 3,484 rules (basically, all of the rules in the security policy)

## Screenshots

Can't post in public - happy to email stuff to you.

## Context

We use the unused to mark rules unused.  With the last hit field being added, I had put in a feature request for this filter (thanks again!) so we could search some arbitrary time since last hit.  Otherwise, we'd have to manually clear the hit counts on all stale rules with hit indicators.  Also, if I recall correctly, the unused filter queries a field that gets reset when the firewall is rebooted.

## Your Environment

- Version used: PANOS 9.1.13-h3
- Environment name and version: PAN-OS-PHP v2.0.38
- Operating System and version (desktop or mobile): Windows 10 21H2 running in PowerShell

**Comment by swaschkut** [comment]
please allow me some questions regarding your filter:

1) 'filter=!(timestamp-last-hit.fast < - 180 days)'
2) 'filter=!(timestamp-last-hit.fast > - 180 days)'

example for 1)
if timestamp-last-hit-fast is 2021 Dec 11th 00::00::00;
then:
- timestamp value for 2022 Jul 11th - 180 days => 2022 Jan 12
       !(  163918088 < 1641945600 ) => timestamp-last-hit is lower then the timestamp before 180 days; but your negating it => so wrong

I assume your are searching for timestamp-last-hit before -180 days.

so you need for example 1) the following filter; which is also state in the list filters example:
pan-os-php type=rule list filters

**(timestamp-last-hit.fast < -180 days)**

or 
**(timestamp-last-hit.fast < 1 February 2022 )**

or US syntax MM/DD/YYYY
**(timestamp-last-hit.fast < 02/01/2022 )**

or European syntax DD-MM-YYYY
**(timestamp-last-hit.fast < 01-02-2022 )**
