### ISSUE TITLE
Service Merger when using PickFilter - Replace objects matching pickfilter with mergeWithUpperLevel

### ISSUE THREAD

**Issue by taddairpanw** [PaloAltoNetworks/pan-os-php#625]
### Is your feature request related to a problem?
Yes - you added a feature for address-merger that enhanced this behavior in 2.0.51. 
When using the Pickfilter in type=service-merger, it keeps whatever the highest level object is in a device group even if it does not match the Pickfilter. 

### Describe the solution you'd like
Apply the same logic you applied in 2.0.51 with the enhancement but for servicemerger: 
"improvements for:  type=address=merger 'allowmergingwithupperlevel' 'pickfilter=( [FILTER] )"

### Describe alternatives you've considered
I have not considered alternatives because the address merger enhancement works so nicely :)

### Additional context

I am trying to deduplicate services in a large Panorama config file and keep all the ones that begin with a naming convention of ^[tTuU][dDcC][pP]-PORTNUMS in the pick filter. It's keeping ones that have an undesirable naming convention for my customer.

**Comment by swaschkut** [comment]
Hi Tom,

I did code cleaning, and improved the merger functionality for the whole class MERGER.php;
the functionality which was planned to be introduced in 2.0.51 for all merger UTILs is now available in 2.0.53

#626
