### ISSUE TITLE
Option to include child DGs in location filter

### ISSUE THREAD

**Issue by necebeci** [PaloAltoNetworks/pan-os-php#634]
### Describe the solution you'd like
An optional parameter for location filter to include all child DGs of the specified DG.
location=DG-A:checkAllchildDG

**Comment by swaschkut** [comment]
please validate on develop Docker Container:

`docker run --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

`pan-os-php type=stats in=xyz exportcsv=file.csv location=DGname:includeChildDgs`

`pan-os-php type=stats in=xyz exportcsv=file.csv location=DGname:excludeMainDg`


Please be aware that for type=stats; ALWAYS the main Panorama config and shared information is displayed

**Comment by swaschkut** [comment]
introduced with PR: #646
