### ISSUE TITLE
Support location argument for stats export to csv

### ISSUE THREAD

**Issue by necebeci** [PaloAltoNetworks/pan-os-php#635]
### Describe the solution you'd like
Recently added feature to export config stats only works for 'shared' section of config
Please make it also available to use with location argument
pan-os-php type=stats in=config.xml exportcsv=stats.csv **location=any**

**Comment by swaschkut** [comment]
right now available in develop docker container:

`docker run  --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

`pan-os-php type=stats in=xyz exportcsv=file.csv location=any`

will be published in master by end of this week

**Comment by swaschkut** [comment]
introduced with PR: #646
