### ISSUE TITLE
filter seems ignored when passing through rewriteXML

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#636]
## Describe the bug
pan-os-php type=address in=OS_20220815_13h00_fixed_rename_fqdn 'actions=name-rename:host.siege.xprod_$$value.no-netmask$$-$$netmask$$' 'filter=(!(object is.group) and (ip.count = 1) and (value ip4.included-in 10.254.0.0/16))' 

this also occurs when adding to filter !(object is.dynamic)

## Current behavior

* ** ERROR ** * ^[[0munsupported rewriteXML for dynamic group
 
 *** Backtrace ***
0 ****
       ^[[1mbacktrace_print^[[0m()
       ::/tools/pan-os-php/lib/pan_php_framework.php line 578
1 ****
       ^[[1mderr^[[0m()
       ::/tools/pan-os-php/lib/object-classes/AddressGroup.php line 633
2 ****
   PanoramaConf: / DeviceGroup:MFTV / AddressStore:address / AddressGroup:grp-clients.adobe.licences-dynamic
       ^[[1mAddressGroup::rewriteXML()^[[0m @
           /tools/pan-os-php/lib/object-classes/AddressGroup.php line 305
3 ****
   PanoramaConf: / DeviceGroup:MFTV / AddressStore:address / AddressGroup:grp-clients.adobe.licences-dynamic
       ^[[1mAddressGroup::referencedObjectRenamed()^[[0m @
           /tools/pan-os-php/lib/misc-classes/trait/ReferenceableObject.php line 87

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

docker pan-os-php:develop

**Comment by swaschkut** [comment]
Addressgroup.php
Around line 300

If( $this->isDynamic() )
         Return null;

**Comment by swaschkut** [comment]
fixed with PR: #642
