### ISSUE TITLE
playbook not interpreting move:LOCATION

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#637]
## Describe the bug
**when running**: output is ok
` pan-os-php type=tag in=configs/OS_20220815_13h00_orig location=MFTV,AIRFAB,PCI-PRA,PPR-NFAB,XFAB,XINT,XPART,XPROD,XPROD-NODAL,XSGP,XSHARE-ADMIN,XSHARE-GUEST,XSHARE-LAN_FTV,XSHARE-SERIAL,XSOS-NFAB,XTT-VPN,XWEB 'actions=move:MFTV,removeIfMatch'`

***********************************************
*********** pan-os-php.php type=tag UTILITY **************

 - PAN-OS-PHP version: 2.0.56 [UNIX] [7.4.3]
 - Reading XML file from disk... configs/OS_20220815_13h00_orig
 - Detected platform type is 'panorama'
 - No 'template' provided so using default ='any'
 - Loading configuration through PAN-OS-PHP library... 
   (2.95 seconds, 134 mb memory)
 - PAN-OS version: 101
 - PAN-OS APP-ID version: 8597-7479
 - PAN-OS Device timezone: Europe/Paris is used. actual time: 2022/08/19 08:03:12

* processing store 'PanoramaConf: / DeviceGroup:MFTV / TagStore:tags' that holds 158 objects
   - object 'FTV-PUBLIC' passing through Action='move' **Args: location=MFTV, mode=removeifmatch,** 
      *** SKIPPED : because original and target destinations are the same: MFTV

**However when using playbook**
`    {
        "type": "address",
        "actions": "actions=move:MFTV,removeIfMatch",
        "shadow-ignoreinvalidaddressobjects": "shadow-ignoreinvalidaddressobjects"
      }`
**the output is**
############################################################################
[ pan-os-php type=tag  location=MFTV,AIRFAB,PCI-PRA,PPR-NFAB,XFAB,XINT,XPART,XPROD,XPROD-NODAL,XSGP,XSHARE-ADMIN,XSHARE-GUEST,XSHARE-LAN_FTV,XSHARE-SERIAL,XSOS-NFAB,XTT-VPN,XWEB **actions=move:shared,removeIfMatch** shadow-ignoreinvalidaddressobjects projectfolder=results in=stages/stage-30.xml out=stages/stage-40.xml ]
***********************************************
*********** PLAYBOOK__.php type=tag UTILITY **************

 - PAN-OS-PHP version: 2.0.56 [UNIX] [7.4.3]
 - Reading XML file from disk... stages/stage-30.xml
 - Detected platform type is 'panorama'
 - No 'template' provided so using default ='any'
 - Loading configuration through PAN-OS-PHP library... 
   (3.47 seconds, 130 mb memory)
 - PAN-OS version: 101
 - PAN-OS APP-ID version: 8597-7479
 - PAN-OS Device timezone: Europe/Paris is used. actual time: 2022/08/19 08:13:58

* processing store 'PanoramaConf: / DeviceGroup:MFTV / TagStore:tags' that holds 129 objects
   - object 'FTV-PUBLIC' passing through Action='move' **Args: location=shared**, mode=removeifmatch, 
      * moved, no conflict

## Expected behavior

* processing store 'PanoramaConf: / DeviceGroup:MFTV / TagStore:tags' that holds 158 objects
   - object 'FTV-PUBLIC' passing through Action='move' **Args: **location=MFTV**, mode=removeifmatch,** 
      *** SKIPPED : because original and target destinations are the same: MFTV

## Current behavior

* processing store 'PanoramaConf: / DeviceGroup:MFTV / TagStore:tags' that holds 129 objects
   - object 'FTV-PUBLIC' passing through Action='move' **Args: location=shared**, mode=removeifmatch, 
      * moved, no conflict

## Your Environment
docker swaschkut/pan-os-php:develop

**Comment by swaschkut** [comment]
You need to specify the location argument in the playbook json file.

if no location is defined:
Location=shared is used per default
