### ISSUE TITLE
adding parameter "location" to playbook.json

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#638]
### Is your feature request related to a problem?
no

### Describe the solution you'd like
when using playbooks, there is not the possibility to specify the location for a specific action in the playbook.json
however I would like to apply different actions based on the DG within one json

### Describe alternatives you've considered
build various playbooks and run them against the needed DG's

### Additional context
something like this should be possible

```
    {
      "type": "address-merger",
      **"location": "DG, DG1, DG2...."**
      "DupAlgorithm": "SameAddress",
      "exportcsv": "address_merger.html",
      "allowmergingwithupperlevel": "allowmergingwithupperlevel",
      "shadow-ignoreinvalidaddressobjects": "shadow-ignoreinvalidaddressobjects"
    },
    {
      "type": "addressgroup-merger",
       **"location": "DG, DG3, DG4...."**
      "DupAlgorithm": "SameIP4Mapping",
      "exportcsv": "address_grp_merger.html",
      "allowmergingwithupperlevel": "allowmergingwithupperlevel",
      "shadow-ignoreinvalidaddressobjects": "shadow-ignoreinvalidaddressobjects"
    },
```

**Comment by swaschkut** [comment]
Same as on other issue:

“location”: “location=dg1,dg2”
