### ISSUE TITLE
DupAlgorithm not parsed properly in playbook.json

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#639]
## Describe the bug
using following:
```
{
  "command": [
    {
      "type": "address-merger",
      "DupAlgorithm": "SameAddress",
      "exportcsv": "address_merger.html",
      "allowmergingwithupperlevel": "allowmergingwithupperlevel",
      "shadow-ignoreinvalidaddressobjects": "shadow-ignoreinvalidaddressobjects"
    }
  ]
}
```

## Expected behavior

[ pan-os-php type=address-merger  location=MFTV,AIRFAB,PCI-PRA,PPR-NFAB,XFAB,XINT,XPART,XPROD,XPROD-NODAL,XSGP,XSHARE-ADMIN,XSHARE-GUEST,XSHARE-LAN_FTV,XSHARE-SERIAL,XSOS-NFAB,XTT-VPN,XWEB **DupAlgorithm=SameAddress** address_merger.html allowmergingwithupperlevel shadow-ignoreinvalidaddressobjects projectfolder=results in=configs/OS_20220815_13h00_orig out=stages/stage-0.xml ]

## Current behavior
[ pan-os-php type=address-merger  location=MFTV,AIRFAB,PCI-PRA,PPR-NFAB,XFAB,XINT,XPART,XPROD,XPROD-NODAL,XSGP,XSHARE-ADMIN,XSHARE-GUEST,XSHARE-LAN_FTV,XSHARE-SERIAL,XSOS-NFAB,XTT-VPN,XWEB **SameAddress** address_merger.html allowmergingwithupperlevel shadow-ignoreinvalidaddressobjects projectfolder=results in=configs/OS_20220815_13h00_orig out=stages/stage-0.xml ]

***********************************************
*********** PLAYBOOK__.php type=address-merger UTILITY **************

 - PAN-OS-PHP version: 2.0.56 [UNIX] [7.4.3]

****ERROR** unsupported argument provided: 'sameaddress'**

* ** WARNING ** * unsupported argument provided: 'sameaddress'

USAGE: php MERGER.php in=inputfile.xml [out=outputfile.xml] location=shared [DupAlgorithm=XYZ] [MergeCountLimit=100] ['pickFilter=(name regex /^H-/)'] ...
## Additional info
behaviour seems to be the same for the argument: **exportcsv**

**Comment by swaschkut** [comment]
Wrong syntax:

{
  "command": [
    {
      "type": "address-merger",
      "DupAlgorithm": "dupalgorithm=SameAddress",
      "exportcsv": "address_merger.html",
      "allowmergingwithupperlevel": "allowmergingwithupperlevel",
      "shadow-ignoreinvalidaddressobjects": "shadow-ignoreinvalidaddressobjects"
    }
  ]
}
