### ISSUE TITLE
Add "UserID-Enable" to type=zone

### ISSUE THREAD

**Issue by taddairpanw** [PaloAltoNetworks/pan-os-php#640]
### Is your feature request related to a problem?
In the Zone util, there is currently no action to enable User ID on the zones which match a filter. 

### Describe the solution you'd like

Add an action called UserID-Enable (and the inverse of UserID-Disable) to enable or disable user ID on zones in a config. 

### Describe alternatives you've considered

Alternatives would be using Expedition to do this, but it can be a good quick alternative to use a one liner to update multiple zones at once. 

### Additional context
One of my team members has a migration that has many contexts (>20), and each context has 7 or 8 interfaces/zones. It would make updating the zones to enable user ID easier.

**Comment by swaschkut** [comment]
implemented with PR: #642
