### ISSUE TITLE
implement variable for description-append

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#641]
### Is your feature request related to a problem?
no
### Describe the solution you'd like

the type=address actions=description-append allows to use stringformula to append the $$current.name$$ however the description-append in the type=service context only allows a string.
I would need to be able to append the current name to services that will be renamed too.

root@9f95e2d77078:/share# pan-os-php `type=address` help description-Append

***********************************************
*********** pan-os-php.php type=address UTILITY **************

 - PAN-OS-PHP version: 2.0.56 [UNIX] [7.4.3]
*** help for Action description-Append:stringFormula

Listing arguments:
-- stringFormula :
 OPTIONAL
 type=string

 This string is used to compose a name. You can use the following aliases :
   - $$current.name$$ : current name of the object
 
root@9f95e2d77078:/share# pan-os-php `type=service` help description-Append

***********************************************
*********** pan-os-php.php type=service UTILITY **************

 - PAN-OS-PHP version: 2.0.56 [UNIX] [7.4.3]
`*** help for Action description-Append:text`

Listing arguments:

-- text :
 OPTIONAL
 type=string

  *no help available*

**Comment by swaschkut** [comment]
implemented with PR: #642
