### ISSUE TITLE
length check when renaming objects with fqdn

### ISSUE THREAD

**Issue by olistr** [PaloAltoNetworks/pan-os-php#643]
### Is your feature request related to a problem?
yes

### Describe the solution you'd like
verify that when renaming objects the name has 63 or less characters, otherwise do not rename

when renaming fqdn objects to the fqdn name, it might happen that the fqdn name is longer than 63 characters which is the limit of object names.
e.g.
```
   - object '[1maptn.pub.keystoneapi.s3aws[0m' passing through Action='name-Rename' Args: stringFormula=$$value$$, 
      * new name will be 'keystoneapi-prod-associatedpressproduction-us-east-1-agentlogs.s3.amazonaws.com'
      *       - renaming object... 
```
when loading into panorama
`-> MFTV -> address -> keystoneapi-prod-associatedpressproduction-us-east-1-agentlogs.s3.amazonaws.com Node can be at most 63 characters, but current length: 79 value: keystoneapi-prod-associatedpressproduction-us-east-1-agentlogs.s3.amazonaws.com... device-group`

### Describe alternatives you've considered

use regex to filter for fqdn objects and no longer than 63  ^[A-Z0-9._%+-]{1,63}$

**Comment by swaschkut** [comment]
introduced in develop branch, will be published with 2.0.57 end of this week
