### ISSUE TITLE
Bug-04092022-1 - error when using "schedule is.expired" filter

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#645]
## Describe the bug

The output ends with the following error

> * processing ruleset 'PanoramaConf: / RuleStore:Security' that holds 96 rules
> 
> * ** ERROR ** * Died on user notice or warning!! Error: Undefined variable: d on /tools/pan-os-php/lib/object-classes/Schedule.php:371
> 
>  *** Backtrace ***
> Provided via Slack
 

 
## Expected behavior

script should export expired rules into Excel

## Steps to reproduce

run command
pan-os-php type=rule in=config.xml location=any 'actions=exporttoexcel:expired-rules.xls' 'filter=(schedule is.expired)'

## Screenshots

additional information provided via Slack

## Your Environment

- Version used: 2.0.56
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Docker
- Operating System and version (desktop or mobile): Windows 10 Pro

**Comment by swaschkut** [comment]
fixed with PR: #646
