### ISSUE TITLE
Rule tag remove based on tag name containing common letters

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#673]
### Is your feature request related to a problem?

It would be nice to be able to remove all tags that contain common lettering.  This is related to the feature request I put in to filter by tag contains.  When I search for previously-tagged unused rules (I have a number of unused tags that all start with "UNUSED-") that are no longer unused, I want to remove all UNUSED tags.  Currently, I have a string of tag-Remove actions for each UNUSED tag I have.

### Describe the solution you'd like

It would be nice to have a tag-Remove action that would operate as something like tag-remove-contains:UNUSED.

### Describe alternatives you've considered

As noted above, I currently remove the tags one at a time.

### Additional context

Like the tag contains filter, it would make it faster to build commands and would avoid errors of omission (or typos).

**Comment by swaschkut** [comment]
already available:

`pan-os-php type=rule 'actions=tag-remove-regex:UNUSED'`

**Comment by bethatasitmay** [comment]
ohhhhh.....guess I'll have to learn regex :-)  Thanks!
