### ISSUE TITLE
Bug-11102022-1 outputformatset doesn't take into account multi-vsys firewall command format

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#677]
## Describe the bug

Executing the following commands produces set commands in a single-vsys format (references to "shared" and "vsys" are missing from the commands)

pan-os-php type=address in=config.xml location=any 'filter=(value is.in.file ip-list.txt)' 'actions=addObjectWhereUsed:1.1.1.1,no' outputformatset=add-1.1.1.1.txt | tee 1.1.1.1-script-output.txt

pan-os-php type=address in=config.xml location=any 'filter=(value ip4.match.exact 4.4.4.4)' 'actions=addObjectWhereUsed:1.1.1.1,no' outputformatset=add-1.1.1.1.txt | tee 1.1.1.1-script-output.txt

## Expected behavior

the following commands should be produced
set vsys vsys1 address-group "GROUP" static 1.1.1.1
set vsys vsys1 rulebase security rules "RULE" source 1.1.1.1

## Current behavior

the following commands are produced
set address-group "GROUP" static 1.1.1.1
set rulebase security rules "RULE" source 1.1.1.1

=======
- Version used: PAN-OS-PHP version: 2.0.62 [UNIX] [7.4.3]
- PAN-OS-PHP in Docker

**Comment by swaschkut** [comment]
bugfix available in Docker develop Container;
will be published in PAN-OS-PHP version 2.1.16

**Comment by swaschkut** [comment]
fixed with #775
