### ISSUE TITLE
Security profile search doesn't show newly added URL categories until touched by an admin.

### ISSUE THREAD

**Issue by groehl321** [PaloAltoNetworks/pan-os-php#686]
## Describe the bug

When running a command to list out the URL categories (non-custom ones), any recently added PA categories don't appear to show up until it has been changed from the default 'allow' action.

## Expected behavior

I would expect that all URL categories would show up regardless of whether they are using the factory default action or not.

## Current behavior

When I run the following on a firewall with the newly received 'encrypted-dns' category, it doesn't show up until I have changed the default action of allow to alert or block.
pan-os-php type=securityprofile securityprofiletype=url-filtering in=api://1.2.3.4 location=any actions=display

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used: 2.0.62
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): PHP 7.4.3
- Operating System and version (desktop or mobile): Desktop Ubuntu 20.04.5 LTS (in VM)
- Link to your project:

**Comment by swaschkut** [comment]
pan-os-php version 2.0.63 is update app-id predefined version;

please use latest available version
