### ISSUE TITLE
Enable filtering of rules based on date of creation or last modification.

### ISSUE THREAD

**Issue by ralchev** [PaloAltoNetworks/pan-os-php#722]
### Is your feature request related to a problem?

It would be helpful if there were filters for when rules were created or modified.

### Describe the solution you'd like

I would like to be able to filter for rules based on when they were created or modified.

The use case is the following.
As new rules are added to the Security Policy, it is not always possible to start with the applications defined. So, engineers leave these rules with services defined only. On many occasions, these port-based rules stay in the Security Policy until a clean-up project is initiated. In large environments (hundreds of DGs, tens of thousands of security rules), this is a pain.
If once a month we could identify security rules there were created or modified in the last 15 days, have hits, but do not have applications defined, we could directly attack these rules and really quickly convert them to App-ID based ones.

### Describe alternatives you've considered

I can use pan-os-php to identify rules that have hits and are configured with applications any. This would reveal not only new rules, but also old ones that maybe already part of a project aiming to convert them to App-ID based ones.
My other option is Panorama and going through each Device Group. But this takes too much time and effort that could be spend on other pressing tasks.

### Additional context
Ideally, we would be able to convert port-based rules to App-ID based ones within 15 or even less days of their creation.

**Comment by swaschkut** [comment]
this filter will be available in version 2.1.11

and is actual available in Docker develop Container, for testing:

`docker run  --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

`pan-os-php type=rule in=api://MGMT-IP 'filter=(timestamp-rule-creation.fast > -50days)'`
