### ISSUE TITLE
Filtering by `hit-count.fast`, `timestamp-last-hit.fast` and `timestamp-first-hit.fast` provides wrong results

### ISSUE THREAD

**Issue by ralchev** [PaloAltoNetworks/pan-os-php#724]
## Describe the bug

Filtering by `hit-count.fast`, `timestamp-last-hit.fast` and `timestamp-first-hit.fast` provides wrong results.

## Expected behavior
Below are attached output of the following commands with debugapi enabled, as well as the rule base in both firewalls in the 'PAN-60-61' Device Group. Rules 7 to 13 (inclusive) are configured in the said Device Group.

`pan-os-php type=rule in=api://192.168.251.7 location='PAN-60-61' actions=exporttoexcel:rules-with-first-hits-before-yesterday.xls 'filter=( timestamp-first-hit.fast < -1 days )' debugapi | tee rules-with-first-hits-before-yesterday.txt`
This request should return 4 out of the 7 rules. Instead, it returns a single rule: 'Allow-Sanctioned-Applications'.

`pan-os-php type=rule in=api://192.168.251.7 location='PAN-60-61' actions=exporttoexcel:rules-with-hits.xls 'filter=( hit-count.fast != 0 )' debugapi | tee rules-with-hits.txt`
This request should return 5 out of 7 rules. Instead, it returns only one rule: 'Allow-Sanctioned-Applications'.

`pan-os-php type=rule in=api://192.168.251.7 location='PAN-60-61' actions=exporttoexcel:rules-with-hits-PAN-60.xls 'filter=( hit-count.fast != 0 )' debugapi | tee rules-with-hits-PAN-60.txt`
This request should return 5 out of 7 rules. Instead, it returns two rules: 'Allow-Linux-Update-Apt' and 'Allow-Sanctioned-Applications'. The difference with the previous request is that only PAN-60 (one of the firewalls in the DG) was running, and PAN-61 was off.

During these tests, no traffic was generated as all hosts were turned off.

## Outputs and Exports

[Here](https://drive.google.com/drive/folders/1cji54VInwBSp-o_5_8_ekny-O-791A2J?usp=sharing), you can find (access for Sven only):
- PAN-60 rule base with hit counts
- PAN-61 rule base with hit counts
- output of pan-os-php for all three commands above

## Context

My goal is to identify rules that do not have hits after a certain date in time.
During tests, I realised I was getting wrong results.

## Your Environment

- Version used: pan-os-php 2.0.69 (develop)
- Operating System and version (desktop or mobile): Ubuntu 22.04 running in Parallels 18.0 on macOS 13.2.

**Comment by swaschkut** [comment]
note for myself,
this is for DGs with multiple devices attached.

**Comment by swaschkut** [comment]
fix introduced with #734 


validation done by issue opener and confirmed, fix is working
