### ISSUE TITLE
PHP 8.2 - not yet supported | PHP Deprecated errors on 2.0.72 after upgrading from 2.0.64

### ISSUE THREAD

**Issue by bethatasitmay** [PaloAltoNetworks/pan-os-php#735]
## Describe the bug

Background:

- I run PAN-OS-PHP in PowerShell
- I install PHP via Chocolatey
- I install PAN-OS-PHP via this method:

`git clone https://github.com/PaloAltoNetworks/pan-os-php.git`

- php.ini parameter 'enable_dl' is set to on (default is off)

Issue:

I upgraded PAN-OS-PHP from 2.0.64 (installed on 12/14/2022 so released on or before 12/14/2022) to 2.0.72 today (2/23/2023) and upgraded PHP 8.1 to 8.2 as I noticed in the changelog for PAN-OS-PHP 2.0.72 that there was a PHP fix mentioned.

## Expected behavior

Well, it should work - in other words, commands that worked on my 2.0.64 install should still work on 2.0.72

For example, I run this every time I upgrade to ensure things are working:

php -r "require_once 'C:/tools/pan/pan-os-php/utils/pan-os-php.php';" type=rule in=api://panorama.domain.com location=any ruletype=security actions=display 'filter=(name contains RULENAME-)'

(we have a ton of rules that are named RULENAME-## across several firewalls managed by Panorama).  As long as PAN-OS-PHP was setup correctly in PowerShell, this always ran correctly and reported all of the filtered rules.

## Current behavior

Complete failure - there are way too many error messages (the exceed the PowerShell buffer - I'll have to figure out how to use Windows Terminal and extend its buffer to get them all or figure out how to pipe PowerShell's output to a file - let me know if you need all of it).

It starts out with making the API connection normally:

'***********************************************
*********** pan-os-php.php type=rule UTILITY **************

PAN-OS-PHP version: 2.0.72 [WIN] [8.2.3]
Downloading config from API...'

And then thousands of PHP Deprecated: Creation of dynamic property errors fly by.  Attached are the last in the buffer (there are thousands of the first two lines).

Something that is interesting is that the normal "preamble" of PAN-OS-PHP is interspersed with the the error messages towards the end.

Detected platform type is 'panorama'
No 'template' provided so using default ='any'
filter after sanitization : (name contains AWS-)
Loading configuration through PAN-OS-PHP library...

## Steps to reproduce

1.  Upgrade to 2.0.72 current version
2.  Upgrade PHP v8.1 to v8.2 (installed & upgraded via Chocolatey)
3.  Update Windows TEMP environment variable to remove PHP81 path
4.  Ensure that php.ini has enable_dl set to on
5.  Run known-working PAN-OS-PHP command

## Context

I am unable to run PAN-OS-PHP 2.0.72.

## Your Environment

- Windows 10 21H2
- PowerShell v5.1 Build 19041.2364
- PHP v8.2
- Version used: 2.0.72 installed 2/23/2023
[PAN-OS-PHP-PHP-Deprecated-errors.txt](https://github.com/PaloAltoNetworks/pan-os-php/files/10819689/PAN-OS-PHP-PHP-Deprecated-errors.txt)

**Comment by swaschkut** [comment]
thanks for already checking on PHP 8.2.

as mentioned on the readme:
https://github.com/PaloAltoNetworks/pan-os-php#old-detailed-information
PHP8.2 is not yet test.

This is a task of improvement and newest PHP version check.
When this will happen, I need to see.

**Comment by swaschkut** [comment]
I recommend to use PHP 8.1 with your Windows installation,

as you are planning to use:
pan-os-php type=certificate

Please also focus that openssl is enabled on your PHP installation.
https://php.tutorials24x7.com/blog/how-to-configure-php-openssl-module-on-windows

**Comment by bethatasitmay** [comment]
I'm not planning to use the type=certificate.  Do I still need to add the openssl module?

Thanks!

**Comment by swaschkut** [comment]
with this I recommend to use pan-os-php 2.0.73 published Feb 24th 08:30am CET;

- validation implemented if php openssl methods are available, if not only warning is displayed
- validation implemented that php version <= 8.1 is used

pan-os-php version 2.0.72 introduce reading of certificates which is relaying on methods from php library openssl

**Comment by swaschkut** [comment]
FYI:
the develop branch, is not containing fixed for PHP 8.2:
https://github.com/swaschkut/pan-os-php

it would be good if you can validate this in your environment.
As soon as I get feedback from you about a working situation,
I will publish this in the main branch

**Comment by bethatasitmay** [comment]
It looks like the dev build works w/ PHP 8.2 except for one item:

'PHP Deprecated:  Creation of dynamic property AppFilter::$subcategory is deprecated in C:\tools\pan\dev\pan-os-php\lib\object-classes\AppFilter.php on line 107'

(repeated 6 times for a total of 7 lines)

I can't remember - are the backtrace messages expected in a dev build?

'* ** WARNING ** * your PHP installation does not contain support for openssl - libraries missing

 *** Backtrace ***
0 ****
       backtrace_print()
       ::C:\tools\pan\dev\pan-os-php\lib\pan_php_framework.php line 767
1 ****
       mwarning()
       ::C:\tools\pan\dev\pan-os-php\lib\network-classes\Certificate.php line 251
2 ****
   PanoramaConf: / Template:DG1 / CertificateStore:certificateStore / Certificate:MyCompany-Root-Sep2041
       Certificate::load_from_domxml() @
           C:\tools\pan\dev\pan-os-php\lib\object-classes\ObjStore.php line 302
3 ****
   PanoramaConf: / Template:DG1 / CertificateStore:certificateStore
       ObjStore::load_from_domxml() @
           C:\tools\pan\dev\pan-os-php\lib\device-and-system-classes\Template.php line 95
4 ****
   PanoramaConf: / Template:DG1
       Template::load_from_domxml() @
           C:\tools\pan\dev\pan-os-php\lib\device-and-system-classes\PanoramaConf.php line 1076
5 ****
   PanoramaConf:
       PanoramaConf::load_from_domxml() @
           C:\tools\pan\dev\pan-os-php\utils\lib\UTIL.php line 1165
6 ****
       UTIL::load_config() @
           C:\tools\pan\dev\pan-os-php\utils\lib\UTIL.php line 312
7 ****
       UTIL::utilActionFilter() @
           C:\tools\pan\dev\pan-os-php\utils\lib\RULEUTIL.php line 30
8 ****
       RULEUTIL::utilStart() @
           C:\tools\pan\dev\pan-os-php\utils\lib\UTIL.php line 197
9 ****
       UTIL::__construct() @
           C:\tools\pan\dev\pan-os-php\lib\misc-classes\PH.php line 980
10 ****
       callPANOSPHP()
       ::C:\tools\pan\dev\pan-os-php\utils\pan-os-php.php line 117
11 ****
       require_once()
       ::Command line code line 1'

**Comment by bethatasitmay** [comment]
Do you want me to test 2.0.73 on PHP 8.1?

**Comment by swaschkut** [comment]
I did some more improvements for develop repository on GitHub:
https://github.com/swaschkut/pan-os-php


regarding 'v' -
can you please retest after updating from:

php -r "require_once 'C:/tools/pan/dev/pan-os-php/utils/pan-os-php.php';" type=version


the two deprecated output should be also cone

**Comment by bethatasitmay** [comment]
Confirmed - latest dev looks good!

**Comment by swaschkut** [comment]
I will close this issue, and publish new version during this week
