### ISSUE TITLE
FR-02-may-2023-1 Add a column for NAT type and rename a column in ExportToExcel action

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#745]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

1) rename the "type" column in the Excel export action to "rule type" (column C in the screenshot)
2) add a new column "nat type" between the current "type" and "name" columns (between columns C and D in the screenshot)
    - this extra column would not be displayed during other rule exports (similar to how "snat type" column is present only during NAT rule exports)

### Additional context

- As discussed on Slack; PAN-OS defines a NAT type (ipv4, nat64, nptv6) and this is currently missing in the PAN-OS-PHP filters and ExportToExcel action

![image](https://user-images.githubusercontent.com/20437364/235623102-486c5bc5-38df-4b38-a608-c8135b625306.png)

![image](https://user-images.githubusercontent.com/20437364/235623126-da53bc38-bbe3-44ba-824d-2e7bb87badcc.png)

**Comment by swaschkut** [comment]
this will be resolved in version 2.1.3
develop version has this already fixed

**Comment by swaschkut** [comment]
introduce with #747
