### ISSUE TITLE
Bug-04062023-1 certain filters do not take address groups into account when filtering for destination IP

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#755]
## Describe the bug

The following filters do NOT identify rules with address groups if the filters are targeting "dst" field. However, if "src" field is targeted, these same filters DO indeed identify rules with address groups.

value ip4.match.exact
value is.in.file
value ip4.match.exact.from.file

## Expected behavior

The filters should treat "src" and "dst" fields the same, meaning they should search for the targeted values inside address groups in both instances (not just when dealing with "src" fields).

## Current behavior

explained above

## Possible solution

apply the same address group search function to "dst" as it currently works for "src"

## Steps to reproduce

- list of commands provided via Slack
- configuration file provided via Slack

- Version used:
- PAN-OS-PHP version: 2.1.7 [UNIX]
- /tools/pan-os-php/utils
- PHP version: 8.1.2-1ubuntu2.11

**Comment by swaschkut** [comment]
bug fixed in the actual develop version;

`docker run  --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

https://github.com/swaschkut/pan-os-php

will be published latest by end of this week

**Comment by swaschkut** [comment]
bugfix published with #757
