### ISSUE TITLE
Rule-Marker.php Undefined variable $configOutput

### ISSUE THREAD

**Issue by davis-sean** [PaloAltoNetworks/pan-os-php#756]
## Describe the bug

Rule-marker.php from the AppID-Toolbox fails to run - indicating a undefined variable.

> Died on user notice or warning!! Error: Undefined variable $configOutput on /tools/pan-os-php/appid-toolbox/lib/common.php:654

## Expected behavior

AppID toolbox runs and marks rules for AppID migration.

## Current behavior

Toolbox fails to run with error.

## Possible solution

Define $configOutput variable at beginning of function.

## Steps to reproduce

1. pan-os-php type=appid-toolbox phase=rule-marker in=api://FIREWALL location=vsys1

## Screenshots
![image](https://github.com/PaloAltoNetworks/pan-os-php/assets/71520366/dc901c64-dc48-481b-bd26-e8c9f0b91b91)

## Context

AppID Migration.

## Your Environment

Single vsys firewall - using Docker image of pan-os-php

**Comment by swaschkut** [comment]
hi davis-sean,
thanks for finding and reporting this issue;

there is just a fix published in the develop Docker container,

would be good if you can validate on your side if this is fixing your problem:

`docker run  --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop`

**Comment by davis-sean** [comment]
Hello,
It looks like the issue is still there:

![Error_PAN-OS-PHP](https://github.com/PaloAltoNetworks/pan-os-php/assets/71520366/219a1169-733d-4e51-946c-b0cd0ec9f2c9)

**Comment by swaschkut** [comment]
sorry, yes.
still having problems with hub.docker.com to publish the correct container.
I will update again, as soon as this is correctly published

**Comment by swaschkut** [comment]
please check

**Comment by swaschkut** [comment]
bug fixed in the actual develop version;

docker run  --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop

https://github.com/swaschkut/pan-os-php

will be published latest by end of this week

**Comment by davis-sean** [comment]
The fix appears to have worked. The marking phase went off without issue this time.

**Comment by swaschkut** [comment]
bugfix published with #757
