### ISSUE TITLE
Add new action to work with Group Tags in policy rules (pan-os-php type=rule)

### ISSUE THREAD

**Issue by nikolay-matveev-kkr** [PaloAltoNetworks/pan-os-php#758]
### Is your feature request related to a problem?

It would be great to be able to add/remove Group Tags to rules using  "pan-os-php type=rule" (the current list of actions includes "tag-Add|Add-Force|Remove|Remove-All|Remove-Regex" which work only with regular tags but not with Group Tags)

### Describe the solution you'd like

Add new actions (for example "groupTag-Add|Add-Force|Remove|Remove-Regex")
They should work the same way as the actions for regular tags.

### Describe alternatives you've considered

Manual change, or pan-os-python.

### Additional context

We use Group tags to visually group rules in a policy with many rules.

**Comment by swaschkut** [comment]
Thanks for reaching out:

your feature is already implemented:

based on CHANGELOG.txt - since April 2023:

```
2.0.75 (20230412)
UTIL:
* type=rule | extend with actions=group-tag-remove | group-tag-set:GROUPTAGNAME
```

the actual latest public version is 2.1.8 - and develop version is currently 2.1.9

```
pan-os-php type=rule listactions 
..........
* group-tag-Remove          |
====================================================================
* group-tag-Set             | #1 Group-Tag:string     | *nodefault* | 
.........
```

```
pan-os-php type=rule help group-tag-set

***********************************************
*********** pan-os-php.php type=rule UTILITY **************

 - PAN-OS-PHP version: 2.1.9 [UNIX] [8.2.5]
*** help for Action group-tag-Set:Group-Tag

Listing arguments:


-- Group-Tag :
 OPTIONAL
 type=string

  *no help available*
```

**Comment by swaschkut** [comment]
FYI:
with new version 2.1.9 - right now under development,
there will come a new filter:

type=rule 'filter=(group-tag is.regex /VALUE/)'

**Comment by nikolay-matveev-kkr** [comment]
I was looking right into the list of actions and could not see it. Probably need to get back to studying the alphabet LOL. Thank you so much!

**Comment by swaschkut** [comment]
It is maybe worth to check which version you are running:

pan-os-php version
