### ISSUE TITLE
type=dhcp enhancement request

### ISSUE THREAD

**Issue by madmann26** [PaloAltoNetworks/pan-os-php#767]
### Is your feature request related to a problem?

This is not related to a specific problem.

### Describe the solution you'd like

For type=dhcp, please incorporate the option "exporttoexcel" function to output to an html or csv file.

### Describe alternatives you've considered

I have used "tee" to output to a text file in the meantime.

### Additional context

This would be useful for finding dhcp related config in any DG (edited - meant templates).

**Comment by swaschkut** [comment]
thanks for sending in this FR;
this can maybe worked on end of September 2023;

FYI: DHCP in Panorama config file is part of Template not of DeviceGroup

**Comment by madmann26** [comment]
Thanks Sven,

Yes, the template. I was thinking of template but wrote DG. 😄

**Comment by swaschkut** [comment]
published with #770
