### ISSUE TITLE
Missing master windows zip package

### ISSUE THREAD

**Issue by rolinger** [PaloAltoNetworks/pan-os-php#9]
## Documentation link

The link provided in the home page for the windows binary package:  https://github.com/PaloAltoNetworks/pan-os-php-windows-tool/raw/master/dev.zip - returns a 404

I think this is the package that contains the `setup.bat` file that is mentioned in the `install PAN-OS-PHP.pdf` included in this github distro.

**Comment by swaschkut** [comment]
thanks for reminding me about the Windows package.
yes this missing part includes the `setup.bat` file for setting the correct path variables for PHP to use the framework on Windows.
I am planning to bring the Windows package latest by May 21th.

**Comment by rolinger** [comment]
what does the package provide specifically?  If I recall from years ago I think the main function was to allow PHP to SSH via unix terminal emulator for real time PanOS API interaction.  What else does it enable/provide?

**Comment by swaschkut** [comment]
the windows package provide support to run PAN-OS-PHP scripts directly on Windows.

What this repository does is described in the README, the Windows package only help users to get it running directly on Windows.
There is maybe a plan available to replace the Windows package with WSL2 (Linux command line for Windows)

**Comment by swaschkut** [comment]
in the meantime you can check this:
https://github.com/PaloAltoNetworks/pan-os-php-windows-package/blob/main/dev.zip

with the installation document available here:
https://github.com/PaloAltoNetworks/pan-os-php/blob/developer/Install%20PAN-OS-PHP.pdf

this will be merged with main branch later on this or next week
